import {
  MenuItem,
  EventProfile,
  Ingredient,
  Booking,
  User,
  OperatorSettings,
  Payment,
} from './types';
import { applyBookingValidation } from './alerts';
import { generateInvoice } from './rules/invoices';

export const mockOperatorSettings: OperatorSettings = {
  operatingDays: [1, 2, 3, 4, 5, 6],
  operatingHoursStart: '08:00',
  operatingHoursEnd: '18:00',
  maxEventsPerDay: {
    0: 0,
    1: 1,
    2: 1,
    3: 2,
    4: 2,
    5: 2,
    6: 3,
  },
  maxGuestsPerEvent: 100,
  maxMealPrepFulfillmentsPerDay: {
    0: 0,
    1: 5,
    2: 5,
    3: 5,
    4: 5,
    5: 5,
    6: 3,
  },
  maxServingsPerMealPrepOrder: 20,
};

// Mock Users
export const mockOwner: User = {
  id: 'owner-1',
  name: 'Sarah Chen',
  email: 'sarah@caterflex.com',
  role: 'owner',
};

export const mockCustomers: User[] = [
  {
    id: 'customer-1',
    name: 'James Mitchell',
    email: 'james@example.com',
    role: 'customer',
  },
  {
    id: 'customer-2',
    name: 'Lisa Rodriguez',
    email: 'lisa@example.com',
    role: 'customer',
  },
];

// Mock Menu Items
export const mockMenuItems: MenuItem[] = [
  {
    id: 'menu-1',
    name: 'Herb-Roasted Chicken Breast',
    description: 'Juicy chicken with fresh rosemary and thyme',
    category: 'mains',
    price: 24,
    prepTimeDays: 1,
    macros: { carbs: 8, protein: 45, fat: 12 },
    allergyTags: [],
    requiredIngredients: [
      { id: 'ing-5', name: 'Chicken Breast', qty: 200, unit: 'g' },
      { id: 'ing-1', name: 'Butter', qty: 30, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-2',
    name: 'Spinach & Feta Phyllo Triangles',
    description: 'Crispy pastry with spinach and creamy feta',
    category: 'appetizers',
    price: 14,
    prepTimeDays: 1,
    macros: { carbs: 18, protein: 8, fat: 10 },
    allergyTags: ['dairy', 'gluten'],
    requiredIngredients: [
      { id: 'ing-7', name: 'Feta Cheese', qty: 150, unit: 'g' },
      { id: 'ing-1', name: 'Butter', qty: 40, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-3',
    name: 'Wild Mushroom Risotto',
    description: 'Creamy arborio rice with forest mushrooms',
    category: 'mains',
    price: 20,
    prepTimeDays: 1,
    macros: { carbs: 52, protein: 12, fat: 8 },
    allergyTags: ['dairy'],
    requiredIngredients: [
      { id: 'ing-3', name: 'Arborio Rice', qty: 180, unit: 'g' },
      { id: 'ing-1', name: 'Butter', qty: 50, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-4',
    name: 'Grilled Salmon with Dill',
    description: 'Wild-caught salmon fillet with fresh dill',
    category: 'mains',
    price: 32,
    prepTimeDays: 1,
    macros: { carbs: 4, protein: 38, fat: 18 },
    allergyTags: [],
    requiredIngredients: [
      { id: 'ing-6', name: 'Salmon Fillet', qty: 200, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-5',
    name: 'Roasted Vegetable Medley',
    description: 'Seasonal vegetables with garlic and olive oil',
    category: 'sides',
    price: 12,
    prepTimeDays: 1,
    macros: { carbs: 22, protein: 4, fat: 6 },
    allergyTags: [],
    requiredIngredients: [],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-6',
    name: 'Chocolate Torte with Berries',
    description: 'Rich dark chocolate cake with fresh berries',
    category: 'desserts',
    price: 10,
    prepTimeDays: 2,
    macros: { carbs: 38, protein: 6, fat: 14 },
    allergyTags: ['dairy', 'eggs', 'gluten'],
    requiredIngredients: [
      { id: 'ing-2', name: 'Cocoa Powder', qty: 40, unit: 'g' },
      { id: 'ing-4', name: 'Eggs', qty: 3, unit: 'count' },
      { id: 'ing-1', name: 'Butter', qty: 100, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-7',
    name: 'Shrimp & Garlic Skewers',
    description: 'Gulf shrimp with roasted garlic and lemon',
    category: 'appetizers',
    price: 16,
    prepTimeDays: 1,
    macros: { carbs: 6, protein: 20, fat: 5 },
    allergyTags: ['shellfish'],
    requiredIngredients: [
      { id: 'ing-8', name: 'Shrimp', qty: 150, unit: 'g' },
    ],
    inventoryStatus: 'limited',
  },
  {
    id: 'menu-8',
    name: 'Peanut Sauce Noodle Bowls',
    description: 'Rice noodles with creamy peanut sauce',
    category: 'mains',
    price: 16,
    prepTimeDays: 1,
    macros: { carbs: 48, protein: 14, fat: 12 },
    allergyTags: ['peanuts', 'gluten', 'soy'],
    requiredIngredients: [
      { id: 'ing-9', name: 'Peanut Butter', qty: 80, unit: 'g' },
    ],
    inventoryStatus: 'insufficient',
  },
  {
    id: 'menu-9',
    name: 'Beef Wellington',
    description: 'Tender beef with mushroom duxelles wrapped in pastry',
    category: 'mains',
    price: 38,
    prepTimeDays: 2,
    macros: { carbs: 24, protein: 42, fat: 20 },
    allergyTags: ['gluten', 'eggs'],
    requiredIngredients: [
      { id: 'ing-10', name: 'Beef Tenderloin', qty: 300, unit: 'g' },
      { id: 'ing-1', name: 'Butter', qty: 60, unit: 'g' },
    ],
    inventoryStatus: 'limited',
  },
  {
    id: 'menu-10',
    name: 'Lemon Tart',
    description: 'Tangy lemon curd filling in a buttery pastry shell',
    category: 'desserts',
    price: 12,
    prepTimeDays: 1,
    macros: { carbs: 42, protein: 5, fat: 12 },
    allergyTags: ['dairy', 'eggs', 'gluten'],
    requiredIngredients: [
      { id: 'ing-4', name: 'Eggs', qty: 4, unit: 'count' },
      { id: 'ing-1', name: 'Butter', qty: 80, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-11',
    name: 'Caprese Salad Skewers',
    description: 'Fresh mozzarella, tomato, and basil on a stick',
    category: 'appetizers',
    price: 8,
    prepTimeDays: 0,
    macros: { carbs: 6, protein: 8, fat: 7 },
    allergyTags: ['dairy'],
    requiredIngredients: [
      { id: 'ing-7', name: 'Feta Cheese', qty: 100, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
  {
    id: 'menu-12',
    name: 'Vegetable Quiche',
    description: 'Eggs, cream, and fresh vegetables in a pie crust',
    category: 'mains',
    price: 18,
    prepTimeDays: 1,
    macros: { carbs: 28, protein: 16, fat: 14 },
    allergyTags: ['dairy', 'eggs', 'gluten'],
    requiredIngredients: [
      { id: 'ing-4', name: 'Eggs', qty: 6, unit: 'count' },
      { id: 'ing-1', name: 'Butter', qty: 50, unit: 'g' },
    ],
    inventoryStatus: 'available',
  },
];

// Mock Event Profiles
export const mockEventProfiles: EventProfile[] = [
  {
    id: 'profile-1',
    name: 'Corporate Buffet',
    macros: {
      carbs: { min: 150, max: 250 },
      protein: { min: 80, max: 120 },
      fat: { min: 60, max: 100 },
    },
  },
  {
    id: 'profile-2',
    name: 'Fitness Event',
    macros: {
      carbs: { min: 100, max: 150 },
      protein: { min: 120, max: 180 },
      fat: { min: 40, max: 70 },
    },
  },
  {
    id: 'profile-3',
    name: 'Health-Conscious Gathering',
    macros: {
      carbs: { min: 140, max: 200 },
      protein: { min: 70, max: 110 },
      fat: { min: 50, max: 80 },
    },
  },
];

// Mock Ingredients
export const mockIngredients: Ingredient[] = [
  { id: 'ing-1', name: 'Butter', category: 'dairy', currentStock: 500, unit: 'g', maxCapacity: 1000 },
  { id: 'ing-2', name: 'Cocoa Powder', category: 'baking', currentStock: 200, unit: 'g', maxCapacity: 500 },
  { id: 'ing-3', name: 'Arborio Rice', category: 'pantry', currentStock: 800, unit: 'g', maxCapacity: 2000 },
  { id: 'ing-4', name: 'Eggs', category: 'baking', currentStock: 24, unit: 'count', maxCapacity: 60 },
  { id: 'ing-5', name: 'Chicken Breast', category: 'meats', currentStock: 1500, unit: 'g', maxCapacity: 3000 },
  { id: 'ing-6', name: 'Salmon Fillet', category: 'meats', currentStock: 800, unit: 'g', maxCapacity: 2000 },
  { id: 'ing-7', name: 'Feta Cheese', category: 'dairy', currentStock: 300, unit: 'g', maxCapacity: 800 },
  { id: 'ing-8', name: 'Shrimp', category: 'meats', currentStock: 200, unit: 'g', maxCapacity: 1000 },
  { id: 'ing-9', name: 'Peanut Butter', category: 'pantry', currentStock: 550, unit: 'g', maxCapacity: 500 },
  { id: 'ing-10', name: 'Beef Tenderloin', category: 'meats', currentStock: 600, unit: 'g', maxCapacity: 2000 },
];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: 'booking-1',
    customerId: 'customer-1',
    customerName: 'James Mitchell',
    customerEmail: 'james@example.com',
    eventDate: '2026-07-15',
    eventTime: '12:00',
    eventType: 'Corporate Lunch',
    validationPassed: true,
    ruleViolations: [],
    venue: 'Downtown Conference Center',
    guestCount: 50,
    specialRequests: 'Please avoid shellfish for 2 guests',
    status: 'confirmed',
    selectedMenuItemIds: ['menu-1', 'menu-3', 'menu-6'],
    dietaryRestrictions: [],
    eventProfileId: 'profile-1',
    totalCost: 1200,
    paymentsReceived: 800,
    createdAt: '2026-06-15T10:00:00Z',
    confirmedAt: '2026-06-16T14:30:00Z',
  },
  {
    id: 'booking-2',
    customerId: 'customer-2',
    customerName: 'Lisa Rodriguez',
    customerEmail: 'lisa@example.com',
    eventDate: '2026-07-20',
    eventTime: '17:00',
    eventType: 'Wedding Reception',
    validationPassed: false,
    ruleViolations: ['Guest count (120) exceeds maximum of 100 per event'],
    venue: 'The Grand Ballroom',
    guestCount: 120,
    specialRequests: 'Vegetarian options needed for 15 guests',
    status: 'pending',
    selectedMenuItemIds: ['menu-4', 'menu-5', 'menu-10'],
    dietaryRestrictions: ['dairy', 'gluten'],
    eventProfileId: 'profile-1',
    totalCost: 3600,
    paymentsReceived: 1800,
    createdAt: '2026-06-01T09:00:00Z',
  },
  {
    id: 'booking-3',
    customerId: 'customer-1',
    customerName: 'James Mitchell',
    customerEmail: 'james@example.com',
    eventDate: '2026-08-10',
    eventTime: '10:00',
    eventType: 'Fitness Challenge',
    validationPassed: true,
    ruleViolations: [],
    venue: 'Sports Complex',
    guestCount: 75,
    specialRequests: 'High protein menu preferred',
    status: 'pending',
    selectedMenuItemIds: ['menu-1', 'menu-4', 'menu-5'],
    dietaryRestrictions: [],
    eventProfileId: 'profile-2',
    totalCost: 1800,
    paymentsReceived: 0,
    createdAt: '2026-06-20T15:30:00Z',
  },
  {
    id: 'booking-4',
    customerId: 'customer-2',
    customerName: 'Lisa Rodriguez',
    customerEmail: 'lisa@example.com',
    eventDate: '2026-07-10',
    eventTime: '14:00',
    eventType: 'Birthday Celebration',
    validationPassed: true,
    ruleViolations: [],
    venue: 'Private Residence',
    guestCount: 30,
    specialRequests: 'Extra chocolate desserts',
    status: 'confirmed',
    selectedMenuItemIds: ['menu-2', 'menu-6', 'menu-11'],
    dietaryRestrictions: ['shellfish', 'peanuts'],
    eventProfileId: 'profile-1',
    totalCost: 600,
    paymentsReceived: 600,
    createdAt: '2026-05-20T12:00:00Z',
    confirmedAt: '2026-05-25T16:00:00Z',
  },
  {
    id: 'booking-5',
    customerId: 'customer-1',
    customerName: 'James Mitchell',
    customerEmail: 'james@example.com',
    eventDate: '2026-07-25',
    eventTime: '11:00',
    eventType: 'Product Launch',
    validationPassed: true,
    ruleViolations: [],
    venue: 'Innovation Hub',
    guestCount: 100,
    specialRequests: 'Gluten-free options for 8 guests',
    status: 'pending',
    selectedMenuItemIds: ['menu-7', 'menu-8', 'menu-9'],
    dietaryRestrictions: ['gluten', 'soy'],
    eventProfileId: 'profile-3',
    totalCost: 2400,
    paymentsReceived: 1200,
    createdAt: '2026-06-10T13:45:00Z',
  },
  {
    id: 'booking-6',
    customerId: 'customer-2',
    customerName: 'Lisa Rodriguez',
    customerEmail: 'lisa@example.com',
    eventDate: '2026-07-05',
    eventTime: '18:00',
    eventType: 'Networking Mixer',
    validationPassed: false,
    ruleViolations: ['Event time 18:00 is outside operating hours (08:00–18:00)'],
    venue: 'Downtown Lofts',
    guestCount: 60,
    specialRequests: 'No meat options',
    status: 'confirmed',
    selectedMenuItemIds: ['menu-3', 'menu-5', 'menu-11'],
    dietaryRestrictions: [],
    eventProfileId: 'profile-1',
    totalCost: 900,
    paymentsReceived: 900,
    createdAt: '2026-06-05T11:20:00Z',
    confirmedAt: '2026-06-08T10:00:00Z',
  },
  {
    id: 'booking-7',
    customerId: 'customer-1',
    customerName: 'James Mitchell',
    customerEmail: 'james@example.com',
    eventDate: '2026-08-01',
    eventTime: '09:00',
    eventType: 'Company Retreat',
    validationPassed: true,
    ruleViolations: [],
    venue: 'Mountain Lodge',
    guestCount: 45,
    specialRequests: 'Mix of vegetarian and meat options',
    status: 'pending',
    selectedMenuItemIds: ['menu-1', 'menu-3', 'menu-12'],
    dietaryRestrictions: ['eggs'],
    eventProfileId: 'profile-1',
    totalCost: 1350,
    paymentsReceived: 675,
    createdAt: '2026-06-18T14:00:00Z',
  },
  {
    id: 'booking-8',
    orderType: 'meal_prep',
    customerId: 'customer-2',
    customerName: 'Lisa Rodriguez',
    customerEmail: 'lisa@example.com',
    eventDate: '2026-07-07',
    eventTime: '10:00',
    eventType: 'Weekly Fitness Meal Plan',
    validationPassed: true,
    ruleViolations: [],
    venue: '123 Oak Street — delivery',
    guestCount: 8,
    mealPrepFrequency: 'weekly',
    fulfillmentMethod: 'delivery',
    specialRequests: 'No dairy, high protein portions',
    status: 'confirmed',
    selectedMenuItemIds: ['menu-1', 'menu-4', 'menu-5'],
    dietaryRestrictions: ['dairy'],
    eventProfileId: 'profile-2',
    totalCost: 480,
    paymentsReceived: 240,
    createdAt: '2026-06-22T09:00:00Z',
    confirmedAt: '2026-06-23T11:00:00Z',
  },
];

export const mockPayments: Payment[] = [
  { id: 'pay-1', bookingId: 'booking-1', amount: 800, date: '2026-06-16T14:30:00Z', type: 'down_payment' },
  { id: 'pay-2', bookingId: 'booking-2', amount: 1800, date: '2026-06-02T10:00:00Z', type: 'down_payment' },
  { id: 'pay-3', bookingId: 'booking-4', amount: 600, date: '2026-05-25T16:00:00Z', type: 'full_payment' },
  { id: 'pay-4', bookingId: 'booking-5', amount: 1200, date: '2026-06-11T09:00:00Z', type: 'down_payment' },
  { id: 'pay-5', bookingId: 'booking-6', amount: 900, date: '2026-06-08T10:00:00Z', type: 'full_payment' },
  { id: 'pay-6', bookingId: 'booking-7', amount: 675, date: '2026-06-19T11:00:00Z', type: 'down_payment' },
];

export function buildInitialBookings(): Booking[] {
  const normalized: Booking[] = mockBookings.map((booking) => ({
    orderType: 'catering' as const,
    ...booking,
  }));
  return normalized.map((booking) =>
    applyBookingValidation(booking, mockOperatorSettings, normalized)
  );
}

export function buildInitialInvoices(bookings: Booking[], menuItems: MenuItem[]) {
  return bookings
    .filter((b) => b.status === 'confirmed')
    .map((b) => generateInvoice(b, menuItems, mockPayments));
}
